#ifndef _SVR_CMD_H_
#define _SVR_CMD_H_

int  svrProcessCommand(int sock, unsigned char *buf, int svrSize);
int  StoreTerminal(int sock, unsigned char *data, int *DataSize);
int  StoreOperation(int sock, unsigned char *data, int *DataSize);
int  StoreAccessDoor(int sock, unsigned char *data, int *DataSize);
int  StoreAccessPoint(int sock, unsigned char *data, int *DataSize);
int  StoreHoliday(int sock, unsigned char *data, int *DataSize);
int  StoreTimeZone(int sock, unsigned char *data, int *DataSize);
int  StoreSchedule(int sock, unsigned char *data, int *DataSize);
int  StoreUser(int sock, unsigned char *data, int *DataSize);
int  StoreUserEx(int sock, unsigned char *data, int *DataSize);
int  StorePhone(int sock, unsigned char *data, int *DataSize);
int  GetTerminal(int sock, unsigned char *data, int *DataSize);
int  GetOperation(int sock, unsigned char *data, int *DataSize);
int  GetAccessDoor(int sock, unsigned char *data, int *DataSize);
int  GetAccessPoint(int sock, unsigned char *data, int *DataSize);
int  GetHoliday(int sock, unsigned char *data, int *DataSize);
int  GetTimeZone(int sock, unsigned char *data, int *DataSize);
int  GetSchedule(int sock, unsigned char *data, int *DataSize);
int  GetUser(int sock, unsigned char *data, int *DataSize);
int  GetUserEx(int sock, unsigned char *data, int *DataSize);
int  GetPhone(int sock, unsigned char *data, int *DataSize);
int  GetExTerminal(int sock, unsigned char *data, int *DataSize);
int  SetTerminal(int sock, unsigned char *data, int *DataSize);
int  DeleteHoliday(int sock, unsigned char *data, int *DataSize);
int  DeleteTimeZone(int sock, unsigned char *data, int *DataSize);
int  DeleteSchedule(int sock, unsigned char *data, int *DataSize);
int  DeleteUser(int sock, unsigned char *data, int *DataSize);
int  DeleteUserEx(int sock, unsigned char *data, int *DataSize);
int  DeletePhone(int sock, unsigned char *data, int *DataSize);
int  ExportFile(int sock, unsigned char *data, int *DataSize);
int  ExportTerminal(int sock, unsigned char *data, int *DataSize);
int  ExportHolidays(int sock, unsigned char *data, int *DataSize);
int  ExportTimeZones(int sock, unsigned char *data, int *DataSize);
int  ExportSchedules(int sock, unsigned char *data, int *DataSize);
int  ExportUsers(int sock, unsigned char *data, int *DataSize);
int  ExportFPTemplates(int sock, unsigned char *data, int *DataSize);
int  ExportUserExs(int sock, unsigned char *data, int *DataSize);
int  ExportUserPhotos(int sock, unsigned char *data, int *DataSize);
int  ExportPhones(int sock, unsigned char *data, int *DataSize);
int  ExportFPImage(int sock, unsigned char *data, int *DataSize);
int  ExportFirmware(int sock, unsigned char *data, int *DataSize);
int  ImportFile(int sock, unsigned char *data, int *DataSize);
int  ImportTerminal(int sock, unsigned char *data, int *DataSize);
int  ImportHolidays(int sock, unsigned char *data, int *DataSize);
int  ImportTimeZones(int sock, unsigned char *data, int *DataSize);
int  ImportSchedules(int sock, unsigned char *data, int *DataSize);
int  ImportUsers(int sock, unsigned char *data, int *DataSize);
int  ImportFPTemplates(int sock, unsigned char *data, int *DataSize);
int  ImportUserExs(int sock, unsigned char *data, int *DataSize);
int  ImportUserPhotos(int sock, unsigned char *data, int *DataSize);
int  ImportPhones(int sock, unsigned char *data, int *DataSize);
int  ImportFPImage(int sock, unsigned char *data, int *DataSize);
int  ImportFirmware(int sock, unsigned char *data, int *DataSize);
int  GetTerminalStatus(int sock, unsigned char *data, int *DataSize);
int  GetAccessDoorStatus(int sock, unsigned char *data, int *DataSize);
int  AccessControl(int sock, unsigned char *data, int *DataSize);
int  OutputControl(int sock, unsigned char *data, int *DataSize);
int  SetLockOpen(void);
int  ReleaseLockOpen(void);
int  CamControl(int sock, unsigned char *data, int *DataSize);
int  ResetPassback(int sock, unsigned char *data, int *DataSize);
int  RemoteEnrollUser(int sock, unsigned char *data, int *DataSize);
int  AuthenticationResult(int sock, unsigned char *data, int *DataSize);
void DumpFlash(int sock, unsigned char *buf);

#endif
