	v = UIviewWithTag(view, TAG_ADM_LABEL+0);
	sprintf(idstr, "%ld", user->id);
	UIsetText(v, idstr);
	GetUserAccessMode((int)user->accessMode, temp);
	v = UIviewWithTag(view, TAG_ADM_LABEL+1);
	UIsetText(v, temp);
	GetUserAccessRights(user->accessRights, temp);
	v = UIviewWithTag(view, TAG_ADM_LABEL+2);
	UIsetText(v, temp);
	GetUserDate(user->activateDate, temp);
	v = UIviewWithTag(view, TAG_ADM_LABEL+3);
	UIsetText(v, temp);
	GetUserDate(user->expireDate, temp);
	v = UIviewWithTag(view, TAG_ADM_LABEL+4);
	UIsetText(v, temp);
	GetUserCardData(user->cardData, temp);
	v = UIviewWithTag(view, TAG_ADM_LABEL+7);
	UIsetText(v, temp);
	plainbcd2password(user->pin, 8, temp);
	v = UIviewWithTag(view, TAG_ADM_LABEL+8);
	UIsetText(v, temp);

