#ifndef _MSG_H_
#define _MSG_H_


#define MAX_MSGS_COUNT		21

#define M_MAKER_NAME				0
#define M_ENTER_USER_ID				1
#define M_VERIFY_USER_ID			2
#define M_ENTER_PASSWORD			3
#define M_VERIFY_PASSWORD			4
#define M_ENTER_NEW_PW				5
#define M_VERIFY_NEW_PW				6
#define M_PLACE_YOUR_FINGER			7
#define M_PLACE_YOUR_FINGER_AGAIN	8
#define M_TOUCH_YOUR_CARD			9
#define M_TOUCH_YOUR_CARD_AGAIN		10
#define M_ONE_MORE_TIME_PLEASE		11
#define M_YYMMDD					12
#define M_HHMMSS					13
#define M_SECOND					14
#define M_ALWAYS					15
#define M_DETETE_CONFIRM			16
#define M_DIAL_EXT_NUMBER			17
#define M_ENTER_SPEED_DIAL_NNUMBER	18
#define M_ARE_YOU_REALLY			19
#define M_WAIT_A_MOMENT				20

#define MAX_RSP_MSGS_COUNT	61

#define R_PROCESSING				0
#define R_MSG_SYSTEM_ERROR			1
#define R_INPUT_TIME_OVER			2
#define R_INVALID_USER_ID			3
#define R_INVALID_DATA				4
#define R_USER_NOT_FOUND			5
#define R_ACCESS_DENIED				6
#define R_ACCESS_GRANTED			7
#define R_USER_ID_OVERLAPPED		8
#define R_CARD_DATA_OVERLAPPED		9
#define R_FP_DATA_OVERLAPPED		10
#define R_PW_MISMATCHED				11
#define R_DATA_MISMATCHED			12
#define R_DATA_SAVED				13
#define R_USER_DELETED				14
#define R_ALL_USER_DELETED			15
#define R_INVALID_TIME_INTERVAL		16
#define R_INVALID_TID				17
#define R_INVALID_DATE				18
#define R_DATE_CHANGED				19
#define R_INVALID_TIME				20
#define R_TIME_CHANGED				21
#define R_INVALID_IP_ADDRESS		22
#define R_INVALID_SUBNET_MASK		23
#define R_INVALID_GW_ADDRESS		24
#define R_INVALID_SERVER_HOST		25
#define R_INVALID_SERVER_PORT		26
#define R_ALL_DELETED				27
#define R_USER_ARE_FULL				28
#define R_INVALID_EXT_NUMBER		29
#define R_TEL_NO_DIALTONE			30
#define R_TEL_BUSY					31
#define R_TEL_NO_ANSWER				32
#define R_TEL_DISCONNECTED			33
#define R_TEL_CONNECTED				34
#define R_DOOR_UNLOCKED				35
#define R_PROCESSED					36
#define R_FAILED					37
#define R_COMPLETED					38
#define R_NOT_ALLOWED_CARD			39
#define R_TOUCH_SINGLE_CARD			40
#define R_NOT_FOUND					41
#define R_OVERLAPPED				42
#define R_DATA_ARE_FULL				43
#define R_DELETED					44
#define R_NO_SD_DISK				45
#define R_NOT_READY_SD_DISK			46
#define R_DIR_OPEN_ERROR			47
#define R_DIR_READ_ERROR			48
#define R_DIR_WRITE_ERROR			49
#define R_FILE_OPEN_ERROR			50
#define R_FILE_READ_ERROR			51
#define R_FILE_WRITE_ERROR			52
#define R_FILE_SYNC_ERROR			53
#define R_DIRECTORY_NOT_FOUND		54
#define R_FILE_NOT_FOUND			55
#define R_SYSTEM_RESTART			56
#define R_SAFELY_REMOVE_SD_DISK		57
#define R_SD_DISK_ERROR_CHECK		58
#define R_ACCESS_DENIED_FAIL_SERVER 59
#define R_ALREADY_PROCESSING		60

#define MAX_TA_MSGS_COUNT	8

#define MAX_MULTIMSG_LEN			44
#define MAX_MSG_LEN					24
#define MAX_TAMSG_LEN				12

extern unsigned char xrsp_msgs_icon[];

extern char *xmenu_null;
extern char *xmenu_unsupported;
extern char *xmenu_serial_speed[5];

extern char *xmsgs[];
extern char *xrsp_msgs[];
extern char *xta_msgs[];
extern char *xauth_msgs[];
extern char *xmenu_top_title;
extern char *xmenu_top[];
extern char *xmenu_lang[];
extern char *xmenu_user[];
extern char *xmenu_user_enroll[];
extern char *xmenu_access_mode[];
extern char *xmenu_security_level[];
extern char *xmenu_ta_sub[];
extern char *xmenu_time_attend[];
extern char *xmenu_ta_key[];
extern char *xmenu_ta_display[];
extern char *xmenu_ta_item[];
extern char *xmenu_meal[];
extern char *xmenu_meal_sub[];
extern char *xmenu_meal_funckey[];
extern char *xmenu_event[];
extern char *xmenu_event_output[];
extern char *xmenu_event_mask[];
extern char *xmenu_event_wiegand[];
extern char *xmenu_access_control[];
extern char *xmenu_hw_setup[];
extern char *xmenu_op_mode[];
extern char *xmenu_all_readers[];
extern char *xmenu_hw_config[];
extern char *xmenu_unit_type[];
extern char *xmenu_iounit_type[];
extern char *xmenu_access_door[];
extern char *xmenu_door_config[];
extern char *xmenu_door_inout[];
extern char *xmenu_lock_type[];
extern char *xmenu_door_alarm[];
extern char *xmenu_door_alarm_info[];
extern char *xmenu_access_point[];
extern char *xmenu_authorization_mode[];
extern char *xmenu_access_zone[];
extern char *xmenu_passback[];
extern char *xmenu_passback_mode[];
extern char *xmenu_passback_setting[];
extern char *xmenu_binary_input[];
extern char *xmenu_binary_output[];
extern char *xmenu_io_polarity[];
extern char *xmenu_armed[];
extern char *xmenu_alarm[];
extern char *xmenu_fire_zone[];
extern char *xmenu_action_index[];
extern char *xmenu_output_command[];
extern char *xmenu_readers[];
extern char *xmenu_card_readers[];
extern char *xmenu_wiegand_reader[];
extern char *xmenu_fp_reader[];
extern char *xmenu_mifare_reader[];
extern char *xmenu_mifare_format[];
extern char *xmenu_mifare_type[];
extern char *xmenu_special_card[];
extern char *xmenu_data_type[];
extern char *xmenu_byte_order[];
extern char *xmenu_em_format[];
extern char *xmenu_external_format[];
extern char *xmenu_ip_reader[];
extern char *xmenu_wiegand_26bit[];
extern char *xmenu_duress[];
extern char *xmenu_setup[];
extern char *xmenu_admin[];
extern char *xmenu_wiegand_type[];
extern char *xmenu_datetime[];
extern char *xmenu_monitor[];
extern char *xmenu_time_notation[];
extern char *xmenu_date_notation[];
extern char *xmenu_sound[];
extern char *xmenu_lockout[];
extern char *xmenu_cam[];
extern char *xmenu_cam_mode[];
extern char *xmenu_cam_run[];
extern char *xmenu_cam_channel[];
extern char *xmenu_cam_direction[];
extern char *xmenu_doorphone[];
extern char *xmenu_doorphone_op_mode[];
extern char *xmenu_phone_number[];
extern char *xmenu_dialing_mode[];
extern char *xmenu_ip_phone_number[];
extern char *xmenu_ip_phone_item[];
extern char *xmenu_doorphone_volume[];
extern char *xmenu_doorphone_tone[];
extern char *xmenu_tone_info[];
extern char *xmenu_doorphone_hw_setup[];
extern char *xmenu_doorphone_bgn[];
extern char *xmenu_network[];
extern char *xmenu_network_serial[];
extern char *xmenu_serial_port[];
extern char *xmenu_network_tcpip[];
extern char *xmenu_network_mode[];
extern char *xmenu_serial_speed[];
extern char *xmenu_system[];
extern char *xmenu_init_device[];
extern char *xmenu_imexport[];
extern char *xmenu_comm_stats[];
extern char *xmenu_downfirmware[];
extern char *xmenu_inuse[];
extern char *xmenu_yesno[];
extern char *xmenu_noyes[];
extern char *xmenu_okcancel[];
extern char *xmenu_enable;
extern char *xmenu_other[];

void msgInitialize(void);
void GetMonthName(int mm, char *buf);
void GetDayOfWeekName(int wday, char *buf);


#endif	/* _MSG_H_ */