#ifndef _ADM_TITLE_H_
#define _ADM_TITLE_H_


char *admTopTitle(void);

char *admYesTitle(void);
char *admNoTitle(void);
char *admEnableTitle(void);
char *admDisableTitle(void);
char *admConfirmTitle(void);
char *admCancelTitle(void);
char *admCompleteTitle(void);
char *admSaveTitle(void);
char *admDeleteTitle(void);
char *admBitUnitTitle(void);
char *admDigitUnitTitle(void);
char *admByteUnitTitle(void);
char *admSecondUnitTitle(void);
char *admMinuteUnitTitle(void);

char *admNetworkPortsTitle(void);
char *admUnitsTitle(void);
char *admIounitsTitle(void);
char *admSubdevicesTitle(void);
char *admReadersTitle(void);
char *admInputsTitle(void);
char *admOutputsTitle(void);
char *admDoorsTitle(void);
char *admZonesTitle(void);
char *admFireZonesTitle(void);
char *admIntrusionZonesTitle(void);
char *admElevatorsTitle(void);
char *admInputsOutputsTitle(void);
char *admMasterNetworkPortTitle(void);
char *admSlaveDevicesTitle(void);
char *admSetupNetworkTitle(void);
char *admSetupIpAddressTitle(void);
char *admSetupServerTitle(void);
char *admServerIpAddressTitle(void);
char *admServerIpPortTitle(void);
char *admSetupMasterTitle(void);
char *admMasterIpAddressTitle(void);
char *admMasterIpPortTitle(void);
char *admPingTestTitle(void);
char *admPingRunTitle(void);
char *admMacAddressTitle(void);
char *admIpDhcpEnableTitle(void);
char *admIpAddressTitle(void);
char *admSubnetMaskTitle(void);
char *admDefaultGatewayTitle(void);
char *admIpDhcpDnsEnableTitle(void);
char *admPrimaryDnsServerTitle(void);
char *admSecondaryDnsServerTitle(void);
char *admSerialSpeedTitle(void);
char *admSerialProtocolTitle(void);
char *admWifiSsidTitle(void);
char *admWifiStateTitle(void);
char *admWifiSignalStrengthTitle(void);
char *admWifiChannelTitle(void);
char *admWifiSecurityTitle(void);
char *admWifiForgetTitle(void);
char *admWifiConnectTitle(void);
char *admWifiUnchangedTitle(void);

char *admAddressTitle(void);
char *admDeviceIdTitle(void);
char *admNetworkAddressTitle(void);
char *admModelNameTitle(void);
char *admAssignedToTitle(void);
char *admTypeTitle(void);
char *admChannelTitle(void);
char *admNetworkPortTitle(void);
char *admReaderTitle(void);
char *admReaderDeviceTitle(void);
char *admUnitTitle(void);
char *admUnitChTitle(int chId);
char *admPrimaryReaderTitle(void);
char *admSecondaryReaderTitle(void);
char *admIosetTitle(void);
char *admDoorLockRelayTitle(void);
char *admExitButtonInputTitle(void);
char *admDoorStatusDetectInputTitle(void);
char *admAlarmTitle(void);
char *admAlarmRelayTitle(void);
char *admAlarmCommandTitle(void);
char *admDoorPulseTimeTitle(void);
char *admDoorExPulseTimeTitle(void);
char *admLockTypeTitle(void);
char *admTimeDelayTitle(void);
char *admTimeDelayNormalTitle(void);
char *admDoorOpenTooLongTimeTitle(void);
char *admAlarmInhibitTitle(void);
char *admDoorOpenTooLongAlarmTitle(void);
char *admDoorForcedOpenAlarmTitle(void);
char *admIoPolarityTitle(void);
char *admFireZoneTitle(void);
char *admFireInputsTitle(void);
char *admUnlockDoorsTitle(void);
char *admAlarmRelaysTitle(void);
char *admFormatSettingTitle(void);
char *admAlarmCommandsTitle(void);
char *admInputFormatsTitle(void);
char *admWiegandOutputFormatsTitle(void);
char *admSvrnetRemoteTitle(void);
char *admSlvnetRemoteTitle(void);

char *admKernelVersionTitle(void);
char *admFirmwareVersionTitle(void);
char *admModelTitle(void);
char *admUnlimitedTitle(void);
char *admAllTitle(void);
char *admInputVoltageTitle(void);
char *admBatteryTitle(void);
char *admFileSizeTitle(void);
char *admUnspecifiedTitle(void);
char *admNeverTitle(void);
char *admAlwaysTitle(void);
char *admScheduleTitle(void);
char *admMasterPasswordTitle(void);
char *admEventCountTitle(void);
char *admUserCountTitle(void);


#endif

